version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: cd gsql-parser && npm install
      - run: cd gsql-parser && make test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test